version: "3.8"

services:
  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - flask-mongo-net
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - flask-mongo-net
volumes:
  mongo-data:
networks:
  flask-mongo-net:
    external: true

