version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: