version: "3.8"

services:
  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - flask-mongo-net
networks:
  flask-mongo-net:
    external: true

